# Generated by Django 2.0 on 2017-12-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name='created predicted')),
                ('category', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
